pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/gmuthu22k/jenkins-job-repo.git'
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t hello-java-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run --rm hello-java-app'
            }
        }
    }
}