pipeline {
    agent any

    stages {
        
        stage('Build Docker image') {
            steps {
                dir('01_BUILD_DEPLOY_JAVA_PROJECT') {
                    sh 'docker build -t hello-java-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run --rm hello-java-app'
            }
        }
    }
}